### ISSUE TITLE
Allow arrays of variables

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiffEq/ModelingToolkit.jl#102]
It would be useful to be able to work with arrays of variables and access them via `x[1]` etc.
JuMP allows things like this, for example.

**Comment by ChrisRackauckas** [comment]
Arrays of variables already exist? Just put variables in an array? Did you mean variables which are arrays?

**Comment by dpsanders** [comment]
Yes I meant variables which are arrays, so that I see `x[1]` inside the `Expression` itself.

**Comment by ChrisRackauckas** [comment]
Yes, that is something we are planning.

**Comment by HarrisonGrodin** [comment]
What would be the advantage of this feature? Couldn't you just use variables and substitute in arrays (rather than scalars) after the symbolic manipulation, or use an array of variables `[x,y,z]` if the values will be different? That way, we won't need separate machinery for manipulating variables (and can take advantage of existing array utilities).

**Comment by ChrisRackauckas** [comment]
Points in manifolds can be written in a local basis that's different sized vectors. I think we want to be able to express these ideas and I'm not sure how to do that with only vectors of variables. This is down the line though.

**Comment by asprionj** [comment]
I don't understand the use case of points in manifolds and a local basis (am not a mathematician :wink:), but for "everyday use", the arrays-of-variables approach could be sufficient, probably with some commodity functions/macros to remove some of the "ugly" stuff:
```julia
@parameters t
x = [Variable(Symbol("x$i"))(t) for i ∈ 1:10]
sys = ODESystem([    D(x[1])     ~ 1 - x[1];
                  @. D(x[2:end]) ~ x[1:end-1] - x[2:end] ])
f = ODEFunction(sys, x, [])
```
