### ISSUE TITLE
Not recognizing unknown or generate function

### ISSUE THREAD

**Issue by ayadlin** [JuliaDiffEq/ModelingToolkit.jl#104]
I tested the code in the main page -

```julia
# Define some variables
@Param t σ ρ β
@Unknown x(t) y(t) z(t)
@Deriv D'~t
```
 
this is my MoedelingToolkit status [961ee093] ModelingToolkit v0.0.2
when trying to test differential equation section got message:

UndefVarError: @Unknown not defined -
If I change @Unkown for @Var

I a can try and run the next step

```julia
eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]
```

but I get an error which makes me think Var is not the correct type here:

MethodError: objects of type Differential are not callable

Stacktrace:
 [1] top-level scope at In[28]:1

finally if I forget about differential equations and go for no linear systems:

```julia

eqs = [0 ~ σ*(y-x),
       0 ~ x*(ρ-z)-y,
       0 ~ x*y - β*z]

ns = NonlinearSystem(eqs)
nlsys_func = generate_function(ns)
```

I get 

UndefVarError: generate_function not defined

Stacktrace:
 [1] top-level scope at In[30]:6

I assume that this is all because the repository is work in progress, but I thought it'd be good to point out the issues.

Take care-

**Comment by ChrisRackauckas** [comment]
Did you do `using ModelingToolkit` first?

**Comment by HarrisonGrodin** [comment]
It seems like you might be using a rather old version of ModelingToolkit. Try entering Pkg mode (hit `]` in the Julia REPL) and typing `up`, and subsequently closing/reopening the Julia REPL and running `using ModelingToolkit`.

**Comment by ayadlin** [comment]
Yes.
I added ModelingToolkit and
Started the code by
using ModelingToolkit

Sorry that wasn’t clear-

A

**Comment by HarrisonGrodin** [comment]
Oh - it's possible that you're using the most recent _tagged_ version, rather than the latest version. In Pkg mode, you should be able to run `]add ModelingToolkit#master` to make sure you have the bleeding-edge features.

**Comment by ayadlin** [comment]
Thanks,
that solved the issue!
