### ISSUE TITLE
Allow `≤` as alias for `<=`

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiffEq/ModelingToolkit.jl#106]
We should allow `≤` and `≥` as aliases for `<=` and `>=`.

**Comment by HarrisonGrodin** [comment]
I believe this already has the intended behavior, based on the internal definitions of `≤` and `≥`:

```julia
julia> x ≤ y
(x < y) | (x == y)

julia> x ≥ y
(y < x) | (y == x)
```
