### ISSUE TITLE
Add gradient, jacobian and hessian functions

### ISSUE THREAD

**Issue by dpsanders** [JuliaDiffEq/ModelingToolkit.jl#109]
Given an `Operation`, it would be great to be able to calculate symbolically its `gradient`, `jacobian` and `hessian` as e.g.
`gradient(ex, [x, y])` or similar.

I believe this is currently possible but could be usefully streamlined.

**Comment by ChrisRackauckas** [comment]
Completed. We should get full documentation soon.
