### ISSUE TITLE
Functors or Interpolation objects as inputs

### ISSUE THREAD

**Issue by AleMorales** [JuliaDiffEq/ModelingToolkit.jl#13]
Many models are characterized by dynamic inputs (a.k.a external forcings). Using functors is a nice way of incorporating such inputs into a model such that, inside the, one uses `forc(t)` and the logic for generating the forcing is described elsewhere (this is often not a property of the model but of the scenario being simulated). Alternatively, one may interpolate from a timetable of values (e.g. with Interpolations.jl) and then do `forc[t]`. 

At the moment it is not possible to incorporate such syntax when build the `Operation` as Julia would try to call the `Variable` or apply the `getindex` method. I am thinking this trick may work:

```julia
t = IndependentVariable(:t)
forc = Variable(:forc, :Forcing, t)
```
 And add the `(t)` or `[t]` during code generation in a later stage. And, of course, have a `Forcing` constructor wrapper.

But maybe I am missing something or there is a better design for this?

**Comment by ChrisRackauckas** [comment]
For `forc(t)` shouldn't that just be a registered function? 

For `forc[t]` we should probably overload `getindex` on variable to make that a lazy operation. We'll need to find out how to define derivatives of this though.

**Comment by AleMorales** [comment]
It is possible to register the functor as a function but it is not enough, because it is a parameter of the model (passed as input, stored in the `p` argument).  It just happens to be a callable object.

**Comment by ChrisRackauckas** [comment]
I see. It would be cool to have that automatically build interpolating functions.

**Comment by ChrisRackauckas** [comment]
Variables are functions now, so this works.
