### ISSUE TITLE
README: Is t a parameter?

### ISSUE THREAD

**Issue by clagms** [JuliaDiffEq/ModelingToolkit.jl#183]
In the README.md instructions, the independent variable `t` shows up as a parameter:
```
# Define some variables
@parameters t σ ρ β
@variables x(t) y(t) z(t)
@derivatives D'~t
```

Is there any reason for this? Or is it a typo?
I tried rerunning the code with what seems to me to be the correct code, and it still works:
```
# Define some variables
@parameters σ ρ β
@variables t x(t) y(t) z(t)
@derivatives D'~t
```

**Comment by ChrisRackauckas** [comment]
It works either way. In some sense, the variables are unknowns, so `t` acts symbolically more like a parameter which is treated as a "known". In reality, the context really resides in the system construction here.

**Comment by clagms** [comment]
Ahh I get it. Thank you! :)
