### ISSUE TITLE
Add Domains for variables.

### ISSUE THREAD

**Issue by jlperla** [JuliaDiffEq/ModelingToolkit.jl#22]
For variables, etc. we need to be able to assign domains.    I would love to see this as the same one used for the differential operators DSL (which I think was your plan)

While the interface could be left very general, the key cases to test for are:
1. Defined on the reals, maybe as a default `Reals`
2. Defined on a compact set of the reals, `RealsInterval(-1.0, 1.0)`. or even not compact `RealsInterval(0.0, inf)`
3. Defined on integers or `Integers` and `IntegersInterval(-3, 4)` and `IntegersInterval(0, inf)`
4. Defined on a discrete subset of a set, `X = [1 4 5 6]` then `FiniteDomain(X)`
5. Finally, it would be nice to have domains on finite numbers of variables with named states.  A few things come to mind:
  - In an enumeration` @enum Fruit apple=1 orange=2 kiwi=3` and `EnumDomain(Fruit)`.  The last domain would be especially useful when working with markov chains and it would be great to be able to write code in terms of the names of states rather than position in a state vector.
   -  I don't really understand enums well in julia, so it could be that it is better to use a finite domain of symbols, `Fruits = (:apple1, :apple2, :apple3)` and `FiniteDomain(Fruits)`

**Comment by ChrisRackauckas** [comment]
>I would love to see this as the same one used for the differential operators DSL (which I think was your plan)

Yup, that's the plan. We should have a bunch of domain types and an untyped domain field for this. Our variable constructor probably needs to start using some kwargs.

**Comment by jlperla** [comment]
In order of priority after continuous (unbounded) variables: I do not need any of the integer domains yet, and don't think we need compact subsets of R yet.  But having a discrete domain would be nice within a few months (i.e. I have a system of differential equations with a discrete state `i =  :L` or `i = :H` in the math where i have a Markov chain between L and H and then another continuous variable x.  So the notation in my math is `v_i(x)`, etc.)

**Comment by ChrisRackauckas** [comment]
>I don't really understand enums well in julia, so it could be that it is better to use a finite domain of symbols, Fruits = (:apple1, :apple2, :apple3) and FiniteDomain(Fruits)

That's pretty much what an enum is BTW.

**Comment by jlperla** [comment]
Perfect.  Then I am happy with enums.

In fact, they may have the advantage that they have the default ordinal position attached to the names?  If so it makes ordering the states of markov chains consistent without any other magic.  i.e. `@enum InnovationType H=1, L=2` then I can easily jump between markov chain symbols and the ordinal position within vectors.

**Comment by ChrisRackauckas** [comment]
>In fact, they may have the advantage that they have the default ordinal position attached to the names? If so it makes ordering the states of markov chains consistent without any other magic. i.e. @enum InnovationType H=1, L=2 then I can easily jump between markov chain symbols and the ordinal position within vectors.

Indeed.

**Comment by ChrisRackauckas** [comment]
Domains have been added to the variables, but no domains have been created.

**Comment by ChrisRackauckas** [comment]
Basic domains have been added.
