### ISSUE TITLE
Incorrect lengths of Jacobians

### ISSUE THREAD

**Issue by lzxnl** [JuliaDiffEq/ModelingToolkit.jl#231]
Define the function

function grad(f,vars) #vars is an array of variables
    if length(f) > 1
        f1 = ModelingToolkit.jacobian(f,vars)
    else
        f1 = ModelingToolkit.gradient(f,vars)
    end
    f2,f2! = ModelingToolkit.build_function(f1,vars,ModelingToolkit.simplified_expr,Val{false})
    return f2
end

Now, try grad([x,y,z],[x,y,z]) after declaring x, y, z to be variables. The result is not a constant identity matrix function, even though it should be. Rather, it's a vector with 9 entries, a flattened form of what the answer should be. Is there a bug somewhere?

**Comment by wupeifan** [comment]
I think currently they flatten all the matrices. You can reshape it yourself. Just a column priority...

**Comment by ChrisRackauckas** [comment]
fixed!
