### ISSUE TITLE
checkbounds=true not working

### ISSUE THREAD

**Issue by ilarioc** [JuliaDiffEq/ModelingToolkit.jl#243]
Hi,
I was trying to use the option ```checkbounds=true``` when creating an ode system but it does not work for the in-place case:

```julia
using ModelingToolkit
@parameters t σ ρ β
@variables x(t) y(t) z(t)
@derivatives D'~t
eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]
de = ODESystem(eqs, t, [x,y,z], [σ,ρ,β])
myode_iip = generate_function(de; checkbounds=true)[2]
```
the result has the ```@inbounds``` macro:
```julia
:((var"##MTIIPVar#403", u, p, t)->begin
          @inbounds begin
                  let (x, y, z, σ, ρ, β) = (u[1], u[2], u[3], p[1], p[2], p[3])
                      var"##MTIIPVar#403"[1] = σ * (y - x)
                      var"##MTIIPVar#403"[2] = x * (ρ - z) - y
                      var"##MTIIPVar#403"[3] = x * y - β * z
                  end
              end
          nothing
      end)
``` 
I think the problem comes from the begin block https://github.com/JuliaDiffEq/ModelingToolkit.jl/blob/6eae2ad6216d2aab3a50c53e516d36396ea7167e/src/utils.jl#L103-L105
leaving only ```$ip_bounds_block``` seems to fix this case and works as expected when ```checkbounds=false```

**Comment by ChrisRackauckas** [comment]
Indeed that's a mistake, fixed in https://github.com/JuliaDiffEq/ModelingToolkit.jl/pull/244 . You can also submit this small patch if you want the credit 👍 . Quite a deep thing to look into and find the correct fix for someone's first issue!

**Comment by ilarioc** [comment]
Thanks for fixing so quickly!
I was looking around and found it, no need for the credit as long as it is fixed.

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
