### ISSUE TITLE
Determinants

### ISSUE THREAD

**Issue by ArnoStrouwen** [JuliaDiffEq/ModelingToolkit.jl#258]
```
using ModelingToolkit
using LinearAlgebra
@variables a,b,c,d
X = [a b;c d]
det(X) # no way to pass, pivot=Val(false) to lu?
det(X,Val(false))
luX = lu(X,Val(false))
det(luX)
```
Is this the easiest way to get determinants to work?

**Comment by ChrisRackauckas** [comment]
Yes: pivoting won't be trace-able so that's the right thing to do. We should probably make this the standard dispatch on Matrix{Operation}
