### ISSUE TITLE
Rename the repository? What should we call ourselves?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/ModelingToolkit.jl#46]
SciCompDSL.jl isn't really a DSL which is causing confusion. It's pretty much a compiler IR for models which is a nice target for DSLs. So we should probably rename, but to what?

- SciCompIR.jl
- ScientificIR.jl
- ModelingIR.jl

etc? No name is really vibing too much for me.

**Comment by AleMorales** [comment]
scir? As a shorter version of ScientificIR. It is similar to scīr, which was an Old English word meaning "clear" or "transparent", which is a nice goal to aspire to in this package.

**Comment by ChrisRackauckas** [comment]
I generally don't like names which are not informative as to what the package is. From Scir.jl I would not be able to guess what the package does.

**Comment by tshort** [comment]
I like `ModelingIR`. `ScientificIR` is fine, too. Many folks won't know what "IR" means, but I think this is okay. Something like `ModelingBase` or `ModelingPlatform` might fit as well.

**Comment by tshort** [comment]
`ModelingKit` or `ModelingToolkit`?

**Comment by ChrisRackauckas** [comment]
I like ModelingToolkit.jl
