### ISSUE TITLE
Overwrite in `operations.jl`

### ISSUE THREAD

**Issue by MasonProtter** [JuliaDiffEq/ModelingToolkit.jl#57]
In line 18 of the master-branch there is
```
Base.convert(::Type{Operation},x::Variable) = Operation(identity,x)
```
and at line 63 there is
```
Base.convert(::Type{Operation},x::Variable) = Operation(identity,Expression[x])
```

which causes a warning when the package is loaded.

**Comment by ChrisRackauckas** [comment]
Delete the first one.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/ModelingToolkit.jl/commit/6d2f4907070295de789057f3ab9334267d3772ba
