### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jlumpe** [JuliaDiffEq/ModelingToolkit.jl#73]
I was really excited to find this package, I have been working on something very similar in Python for a long time but ended up switching to Julia recently for performance reasons. Getting started has been somewhat slow due to the lack of documentation, though. I can try to contribute by creating a skeleton for the docs if that would be helpful.

**Comment by ChrisRackauckas** [comment]
The reason the documentation is lacking is because we are still overhauling some things. It's released and usable, and the README shows how to use it for "standard cases", and when we get the changes done we'll make it more comprehensive.

**Comment by jlumpe** [comment]
Anywhere contributions are needed?

**Comment by ChrisRackauckas** [comment]
@HarrisonGrodin is overhauling how we are doing differentials and making the way we store the IR use the Julia AST more. Good contributions would be to add things that do transforms (like calculating the sensitivity equations) and adding support for Components (i.e. diffeqs that you can stick in other diffeqs to build up large models), but those probably require the AST to be stabilized before doing. So I'm not sure what the best contribution is right now unless you're willing to join in on the IR overhaul, or wait until the end of January (our target for the AST change timeframe)

**Comment by jlumpe** [comment]
How are things going with this? Has the API stabilized somewhat?

**Comment by HarrisonGrodin** [comment]
We're still finalizing a few aspects of the overhaul (re: #103), but the larger structural changes have been implemented. We still don't have documentation beyond the README, and it seems like writing it isn't going to be a short-term priority. However, the internal complexity has been severely reduced during the overhaul, so it should be feasible to navigate the source using the README. (If you have specific questions, feel free to ask me, as well!)

**Comment by jlumpe** [comment]
@HarrisonGrodin since I'm expecting to get a lot of use out of this package I'll probably keep notes on the functions and types that I use, at which point I might as well write out the docstrings for them. I figure filling out some PRs and getting feedback would probably be a good way to learn the API well.

**Comment by ChrisRackauckas** [comment]
The overhaul has been tagged. While I would be reticent to say that MT is somewhere "stable", I think the core is pretty well done now (thanks to @HarrisonGrodin !) and I wouldn't expect the core to change, but there will be lots of feature development from here.

**Comment by jlumpe** [comment]
@ChrisRackauckas Awesome, looking forward to digging into it more. Actually my immediate focus has shifted a bit to implementing some new ODE problem classes, so would it be useful for me to do the same for `DiffEqBase.jl`? I know DiffEqDevDocs is a thing but docstrings for base classes would still be very helpful I think.

**Comment by ChrisRackauckas** [comment]
Yeah we need a lot more docstrings... I'm not sure what your question is though.

**Comment by jlumpe** [comment]
Just wondering if adding docstrings in DiffEqBase would be helpful. Since it seems like it would be I've submitted a PR with my current progress.
