### ISSUE TITLE
What does context mean in this context?

### ISSUE THREAD

**Issue by jpfairbanks** [JuliaDiffEq/ModelingToolkit.jl#83]
The readme says: 
> The core idea behind ModelingToolkit.jl is that mathematical equations require context, and thus any symbolic manipulations and full model specifications requires the ability to handle such context. 

Does context have a specific definition for this package? Is it the variable names and the information about what those variables are for? Like `Dvar` `IVar`, `Parameter`.

**Comment by ChrisRackauckas** [comment]
>Is it the variable names and the information about what those variables are for?

Yes, that's what it means here. So it's like, when you read the description of a stochastic differential equation, you know that dW isn't just a variable name, but actually stands for a differential of Brownian motion, and that theta is a parameter and not a dependent variable, etc. All of these things are required to do things like transform the system to obey positivity constraints, so it needs to be "known" to the symbolic system in some way.
